// Source registry for MCP server discovery
// Centralized registry of MCP server sources

export const OFFICIAL_SERVERS = [
  {
    id: 'mcp/filesystem',
    name: 'Filesystem',
    description: 'Local filesystem operations - read, write, list, search files',
    category: 'utility',
    provider: 'official',
    url: 'https://github.com/modelcontextprotocol/servers/tree/main/src/filesystem',
    transports: ['stdio', 'http+sse'],
    schemaVersion: '2024-11-05',
    tags: ['files', 'io', 'storage'],
  },
  {
    id: 'mcp/github',
    name: 'GitHub',
    description: 'GitHub API integration - issues, PRs, repos, actions',
    category: 'integration',
    provider: 'official',
    url: 'https://github.com/modelcontextprotocol/servers/tree/main/src/github',
    transports: ['stdio'],
    schemaVersion: '2024-11-05',
    tags: ['github', 'code', 'vcs'],
  },
  {
    id: 'mcp/brave-search',
    name: 'Brave Search',
    description: 'Web search via Brave Search API',
    category: 'search',
    provider: 'official',
    url: 'https://github.com/modelcontextprotocol/servers/tree/main/src/brave-search',
    transports: ['stdio'],
    schemaVersion: '2024-11-05',
    tags: ['search', 'web', 'browser'],
  },
  {
    id: 'mcp/sentry',
    name: 'Sentry',
    description: 'Sentry error tracking and issue management',
    category: 'monitoring',
    provider: 'official',
    url: 'https://github.com/modelcontextprotocol/servers/tree/main/src/sentry',
    transports: ['stdio'],
    schemaVersion: '2024-11-05',
    tags: ['errors', 'monitoring', 'debugging'],
  },
  {
    id: 'mcp/slack',
    name: 'Slack',
    description: 'Slack messaging and workspace integration',
    category: 'communication',
    provider: 'official',
    url: 'https://github.com/modelcontextprotocol/servers/tree/main/src/slack',
    transports: ['stdio'],
    schemaVersion: '2024-11-05',
    tags: ['slack', 'chat', 'messaging'],
  },
  {
    id: 'mcp/aws-kb-retrieval',
    name: 'AWS Knowledge Retrieval',
    description: 'Amazon Bedrock Knowledge Base retrieval',
    category: 'ai',
    provider: 'official',
    url: 'https://github.com/modelcontextprotocol/servers/tree/main/src/aws-kb-retrieval',
    transports: ['stdio'],
    schemaVersion: '2024-11-05',
    tags: ['aws', 'bedrock', 'knowledge-base', 'ai'],
  },
  {
    id: 'mcp/sqlite',
    name: 'SQLite',
    description: 'SQLite database operations',
    category: 'database',
    provider: 'official',
    url: 'https://github.com/modelcontextprotocol/servers/tree/main/src/sqlite',
    transports: ['stdio'],
    schemaVersion: '2024-11-05',
    tags: ['database', 'sqlite', 'sql'],
  },
  {
    id: 'mcp/postgres',
    name: 'PostgreSQL',
    description: 'PostgreSQL database operations',
    category: 'database',
    provider: 'official',
    url: 'https://github.com/modelcontextprotocol/servers/tree/main/src/postgres',
    transports: ['stdio'],
    schemaVersion: '2024-11-05',
    tags: ['database', 'postgres', 'sql'],
  },
  {
    id: 'mcp/google-maps',
    name: 'Google Maps',
    description: 'Google Maps API - directions, places, distance',
    category: 'utility',
    provider: 'official',
    url: 'https://github.com/modelcontextprotocol/servers/tree/main/src/google-maps',
    transports: ['stdio'],
    schemaVersion: '2024-11-05',
    tags: ['maps', 'geolocation', 'google'],
  },
  {
    id: 'mcp/everart',
    name: 'Everart',
    description: 'AI image generation via Everart',
    category: 'ai',
    provider: 'official',
    url: 'https://github.com/modelcontextprotocol/servers/tree/main/src/everart',
    transports: ['stdio'],
    schemaVersion: '2024-11-05',
    tags: ['image', 'ai', 'generation'],
  },
];

export const POPULAR_SERVERS = [
  {
    id: 'anthropic/claude-code',
    name: 'Claude Code',
    description: 'Anthropic Claude Code integration for coding tasks',
    category: 'ai',
    provider: 'anthropic',
    url: 'https://docs.anthropic.com/en/docs/claude-code',
    transports: ['stdio'],
    schemaVersion: '2024-11-05',
    tags: ['claude', 'coding', 'ai'],
  },
  {
    id: 'alibaba/dashscope',
    name: 'DashScope',
    description: 'Alibaba Cloud DashScope LLM integration',
    category: 'ai',
    provider: 'alibaba',
    url: 'https://help.aliyun.com/zh/dashscope/',
    transports: ['stdio', 'http'],
    schemaVersion: '2025-01-01',
    tags: ['alibaba', 'llm', 'ai', 'chinese'],
  },
  {
    id: 'baidu/qianfan',
    name: 'Qianfan',
    description: 'Baidu Qianfan LLM and Wenxin ecosystem integration',
    category: 'ai',
    provider: 'baidu',
    url: 'https://cloud.baidu.com/doc/WENXIN/',
    transports: ['stdio', 'http'],
    schemaVersion: '2025-01-01',
    tags: ['baidu', 'llm', 'ai', 'chinese', 'wenxin'],
  },
  {
    id: 'tencent/cloud',
    name: 'Tencent Cloud AI',
    description: 'Tencent Cloud AI services integration (混元, Hunyuan)',
    category: 'ai',
    provider: 'tencent',
    url: 'https://cloud.tencent.com/product/hunyuan',
    transports: ['stdio', 'http'],
    schemaVersion: '2025-01-01',
    tags: ['tencent', 'llm', 'ai', 'chinese', 'hunyuan'],
  },
  {
    id: 'notion/notion-api',
    name: 'Notion API',
    description: 'Notion workspace integration - pages, databases, search',
    category: 'productivity',
    provider: 'notion',
    url: 'https://developers.notion.com/',
    transports: ['stdio'],
    schemaVersion: '2024-11-05',
    tags: ['notion', 'productivity', 'database'],
  },
  {
    id: 'linear/linear-api',
    name: 'Linear',
    description: 'Linear project management integration',
    category: 'productivity',
    provider: 'linear',
    url: 'https://developers.linear.app/',
    transports: ['stdio'],
    schemaVersion: '2024-11-05',
    tags: ['linear', 'project', 'management'],
  },
  {
    id: 'stripe/stripe-api',
    name: 'Stripe',
    description: 'Stripe payment and billing integration',
    category: 'commerce',
    provider: 'stripe',
    url: 'https://stripe.com/docs/developers',
    transports: ['stdio'],
    schemaVersion: '2024-11-05',
    tags: ['stripe', 'payments', 'commerce'],
  },
  {
    id: 'datadog/datadog-api',
    name: 'Datadog',
    description: 'Datadog monitoring and observability integration',
    category: 'monitoring',
    provider: 'datadog',
    url: 'https://docs.datadoghq.com/api/',
    transports: ['stdio'],
    schemaVersion: '2024-11-05',
    tags: ['datadog', 'monitoring', 'observability'],
  },
];

export const SOURCE_REGISTRY = {
  official: {
    name: 'MCP Official Servers',
    url: 'https://github.com/modelcontextprotocol/servers',
    description: 'Official MCP server registry by Anthropic/MCP team',
    priority: 1,
    servers: OFFICIAL_SERVERS,
  },
  popular: {
    name: 'Popular MCP Servers',
    url: null,
    description: 'Well-known third-party MCP server integrations',
    priority: 2,
    servers: POPULAR_SERVERS,
  },
};

export function getAllServers() {
  return [...OFFICIAL_SERVERS, ...POPULAR_SERVERS];
}

export function getServersBySource(source) {
  if (source === 'official') return OFFICIAL_SERVERS;
  if (source === 'popular') return POPULAR_SERVERS;
  return getAllServers();
}

export function getServerById(id) {
  return getAllServers().find((s) => s.id === id) || null;
}